# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/users/gina/onedrive/desktop/dvlsi/lab/zybo_fir/tmp_edit_project.srcs/sources_1/bd/FIR_design/ip/FIR_design_auto_pc_0/FIR_design_auto_pc_0.xci
# IP: The module: 'FIR_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/users/gina/onedrive/desktop/dvlsi/lab/zybo_fir/tmp_edit_project.srcs/sources_1/bd/FIR_design/ip/FIR_design_auto_pc_0/FIR_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/users/gina/onedrive/desktop/dvlsi/lab/zybo_fir/tmp_edit_project.srcs/sources_1/bd/FIR_design/ip/FIR_design_auto_pc_0/FIR_design_auto_pc_0.xci
# IP: The module: 'FIR_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/users/gina/onedrive/desktop/dvlsi/lab/zybo_fir/tmp_edit_project.srcs/sources_1/bd/FIR_design/ip/FIR_design_auto_pc_0/FIR_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
