# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/FIR_design/FIR_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIR_design || ORIG_REF_NAME==FIR_design} -quiet] -quiet

# IP: bd/FIR_design/ip/FIR_design_processing_system7_0_0/FIR_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIR_design_processing_system7_0_0 || ORIG_REF_NAME==FIR_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/FIR_design/ip/FIR_design_FIR_IP_v1_0_S00_AXI_0_0/FIR_design_FIR_IP_v1_0_S00_AXI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIR_design_FIR_IP_v1_0_S00_AXI_0_0 || ORIG_REF_NAME==FIR_design_FIR_IP_v1_0_S00_AXI_0_0} -quiet] -quiet

# IP: bd/FIR_design/ip/FIR_design_auto_pc_0/FIR_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIR_design_auto_pc_0 || ORIG_REF_NAME==FIR_design_auto_pc_0} -quiet] -quiet

# IP: bd/FIR_design/ip/FIR_design_ps7_0_axi_periph_0/FIR_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIR_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==FIR_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/FIR_design/ip/FIR_design_rst_ps7_0_100M_0/FIR_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIR_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==FIR_design_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/FIR_design/FIR_design_ooc.xdc
