webtalk_init -webtalk_dir C:/Users/zoege/OneDrive/Documents/ece/8th semester/dvlsi/Lab1/ExB3/3_bit_counter/3_bit_counter.sim/sim_1/behav/xsim/xsim.dir/count3_tb_rtl_limit_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Mar 14 17:41:53 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b2491883-a0c2-402c-8c74-3addf59e7d1e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "64b7767a2c664bbb9a2c4e04809e06bb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2803 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9888_KB" -context "xsim\\usage"
webtalk_transmit -clientid 994450322 -regid "" -xml C:/Users/zoege/OneDrive/Documents/ece/8th semester/dvlsi/Lab1/ExB3/3_bit_counter/3_bit_counter.sim/sim_1/behav/xsim/xsim.dir/count3_tb_rtl_limit_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/zoege/OneDrive/Documents/ece/8th semester/dvlsi/Lab1/ExB3/3_bit_counter/3_bit_counter.sim/sim_1/behav/xsim/xsim.dir/count3_tb_rtl_limit_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/zoege/OneDrive/Documents/ece/8th semester/dvlsi/Lab1/ExB3/3_bit_counter/3_bit_counter.sim/sim_1/behav/xsim/xsim.dir/count3_tb_rtl_limit_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
