@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Apr 08 16:10:52 +0300 2024
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim full_adder_bh_tb_behav -key {Behavioral:sim_1:Functional:full_adder_bh_tb} -tclbatch full_adder_bh_tb.tcl -view C:/Users/Gina/OneDrive/Desktop/DVLSI/Lab 3/synchronous_FA_MUL/adders_mulyipliers/full_adder_bh_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
